# Generated by Django 5.2.17 on 2026-09-21 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bloodbanks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.PositiveIntegerField()),
                ('collection_date', models.DateField()),
                ('expiry_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('expired', 'Expired'), ('issued', 'Issued')], db_index=True, default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='accounts.bloodgroup')),
                ('bloodbank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='bloodbanks.bloodbank')),
            ],
            options={
                'verbose_name_plural': 'blood inventory',
            },
        ),
    ]
