# Generated by Django 5.2.17 on 2026-09-21 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_blood_groups'),
        ('bloodbanks', '0001_initial'),
        ('bloodrequests', '0002_request_details_and_history'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodinventory',
            options={'ordering': ['expiry_date', 'id'], 'verbose_name_plural': 'blood inventory'},
        ),
        migrations.AlterField(
            model_name='bloodinventory',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('expired', 'Expired'), ('issued', 'Issued'), ('discarded', 'Discarded')], db_index=True, default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('collection', 'Collection'), ('issue', 'Issue / dispatch'), ('expired', 'Expired'), ('adjustment', 'Adjustment')], db_index=True, max_length=20)),
                ('units', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.bloodinventory')),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.bloodgroup')),
                ('bloodbank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='bloodbanks.bloodbank')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='bloodrequests.bloodrequest')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
