# Generated by Django 5.2.17 on 2026-09-21 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donation_options_donation_rejection_reason'),
        ('inventory', '0002_ledger_and_discarded_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='donations.donation'),
        ),
    ]
