# Generated by Django 5.2.17 on 2026-09-21 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodrequests', '0002_request_details_and_history'),
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='DonorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_responses', to='donors.donor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_responses', to='bloodrequests.bloodrequest')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('request', 'donor'), name='one_response_per_donor_per_request')],
            },
        ),
    ]
