export const NAV_ITEMS = {
  admin: [
    { to: '/admin', label: 'Dashboard', end: true },
    { to: '/admin/users', label: 'Users' },
    { to: '/admin/donors', label: 'Donors' },
    { to: '/admin/hospitals', label: 'Hospitals' },
    { to: '/admin/bloodbanks', label: 'Blood banks' },
    { to: '/admin/requests', label: 'Blood requests' },
    { to: '/admin/inventory', label: 'Inventory' },
    { to: '/admin/donations', label: 'Donations' },
    { to: '/admin/reports', label: 'Reports' },
    { to: '/admin/search', label: 'Search' },
  ],
  donor: [
    { to: '/donor', label: 'Dashboard', end: true },
    { to: '/donor/profile', label: 'My profile' },
    { to: '/donor/requests', label: 'Requests near you' },
    { to: '/donor/donations', label: 'Donation history' },
    { to: '/donor/schedule', label: 'Schedule donation' },
  ],
  seeker: [
    { to: '/seeker', label: 'Dashboard', end: true },
    { to: '/seeker/requests', label: 'My requests', end: true },
    { to: '/seeker/requests/new', label: 'New request' },
    { to: '/seeker/search', label: 'Search' },
  ],
  hospital: [
    { to: '/hospital', label: 'Dashboard', end: true },
    { to: '/hospital/profile', label: 'Hospital profile' },
    { to: '/hospital/search', label: 'Search' },
    { to: '/hospital/requests', label: 'Blood requests', end: true },
    { to: '/hospital/requests/new', label: 'New request' },
  ],
  bloodbank: [
    { to: '/bloodbank', label: 'Stock overview', end: true },
    { to: '/bloodbank/profile', label: 'Blood bank profile' },
    { to: '/bloodbank/inventory', label: 'Inventory' },
    { to: '/bloodbank/donations', label: 'Donations' },
    { to: '/bloodbank/issue', label: 'Issue blood' },
    { to: '/bloodbank/history', label: 'Inventory history' },
    { to: '/bloodbank/requests', label: 'Requests' },
    { to: '/bloodbank/search', label: 'Search' },
  ],
}
