# Generated by Django 5.2.17 on 2026-09-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-donation_date', '-id']},
        ),
        migrations.AddField(
            model_name='donation',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
